In [111]:
import pickle
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [108]:
data = pd.read_csv(r'C:\Users\User\GIT\model testing\Ocena-komentarzy-NLP/web_scraping/allegro_scraped1.csv', sep=',', names = ['Sentiment', 'Opinion'],  encoding= 'utf-8')
df = pd.DataFrame(data)
df

      Sentiment                                            Opinion
0             1  Francois Nuyts prezes to jest główny winowajca...
1             1  Allegro to nic innego jak zysk od sprzedaży Na...
2             5  Jestem kupującym-nie sprzedającym i jestem bar...
3             1  Allegro obecnie przypomina Bazar Różyckiego. T...
4             1  Sprzedaż na Allegro Lokalnie bez żadnych  kosz...
...         ...                                                ...
1157          5  Zamówienie złożone online wszystko na plus jeś...
1158          5  spoko loko luz i spontan. Bardzo szybka wysyłk...
1159          5            WSZYSTKO O.K. Tak powinno być wszędzie.
1160          1                  Zamówiony towar nigdy nie dotarł.
1161          5  Cała transakcja przebiegła bardzo sprawnie. Za...

[1162 rows x 2 columns]

In [4]:
print(len(df[df.Sentiment == 1]))
print(len(df[df.Sentiment == 5]))

512
622

In [5]:
df.loc[df['Sentiment'] == 1, 'Sentiment']=0
df.loc[df['Sentiment'] == 5, 'Sentiment']=1

In [6]:
df

      Sentiment                                            Opinion
0             0  Francois Nuyts prezes to jest główny winowajca...
1             0  Allegro to nic innego jak zysk od sprzedaży Na...
2             1  Jestem kupującym-nie sprzedającym i jestem bar...
3             0  Allegro obecnie przypomina Bazar Różyckiego. T...
4             0  Sprzedaż na Allegro Lokalnie bez żadnych  kosz...
...         ...                                                ...
1157          1  Zamówienie złożone online wszystko na plus jeś...
1158          1  spoko loko luz i spontan. Bardzo szybka wysyłk...
1159          1            WSZYSTKO O.K. Tak powinno być wszędzie.
1160          0                  Zamówiony towar nigdy nie dotarł.
1161          1  Cała transakcja przebiegła bardzo sprawnie. Za...

[1162 rows x 2 columns]

In [7]:
# df.to_pickle('corpus1.pkl')

In [114]:
import pandas as pd

data = pd.read_pickle('corpus1.pkl')

In [115]:
import re 
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [122]:
stopwords = pd.read_csv('stopwords.txt', header=None)
stopwords.columns = ['word']
stopwords_list = list(stopwords['word'])
# stopwords_list

In [123]:
def clean_text(text):    
    text = text.lower()
    text = re.sub(r'[\?,!.*]*', '', text) # replacement of what in the square bracket
    text = re.sub('\w*\d\w*', '', text)# remove digits
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub(re.compile(r'\W*\b\w{1,1}\b'), "", text) #remove short words
    text = re.sub('\n', '', text)
    text = text.split()
    text = [word for word in text if not word in stopwords_list] # remove stopwords
    text = ' '.join(text)
    return text

round1 = lambda x: clean_text(x)

In [124]:
data_clean = pd.DataFrame(df.Opinion.apply(round1))
data_clean

                                                Opinion
0     francois nuyts prezes główny winowajca złodzie...
1     innego zysk sprzedaży nabywca frajerod paździe...
2     kupującym-nie sprzedającym zadowolona zakupy c...
3     obecnie przypomina bazar różyckiego tyle różyc...
4     sprzedaż lokalnie kosztów kolejna ściema zakoń...
...                                                 ...
1157  zamówienie złożone online plus chodzi obsługę ...
1158  spoko loko luz spontan szybka wysyłka zamówien...
1159                                        ok wszędzie
1160                             zamówiony towar dotarł
1161  transakcja przebiegła sprawnie zamówienie szyb...

[1162 rows x 1 columns]

In [125]:
data_clean['Sentiment'] = df['Sentiment']
data_clean

                                                Opinion  Sentiment
0     francois nuyts prezes główny winowajca złodzie...          1
1     innego zysk sprzedaży nabywca frajerod paździe...          1
2     kupującym-nie sprzedającym zadowolona zakupy c...          5
3     obecnie przypomina bazar różyckiego tyle różyc...          1
4     sprzedaż lokalnie kosztów kolejna ściema zakoń...          1
...                                                 ...        ...
1157  zamówienie złożone online plus chodzi obsługę ...          5
1158  spoko loko luz spontan szybka wysyłka zamówien...          5
1159                                        ok wszędzie          5
1160                             zamówiony towar dotarł          1
1161  transakcja przebiegła sprawnie zamówienie szyb...          5

[1162 rows x 2 columns]

In [79]:
# df.to_pickle('corpus_cleaned.pkl')

In [126]:
df_x =data_clean['Opinion']
df_y = data_clean['Sentiment']

In [127]:
# Document-Term Matrix - word counts in matrix format
cv = CountVectorizer()
data_cv = cv.fit_transform(data_clean.Opinion)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
data_dtm.index = data_clean.index
data_dtm

,_głupi_,_holaola_,abonamenty,aborcja,absolutnie,absurd,absurdalne,absurdalnej,absurdalnie,absurdem,...,żyje,żyjemy,żyją,żyli,żywicielami,żąda,żądają,żądaniu,żądnego,żązden
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1159,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1160,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1161,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [129]:
# Let's pickle it for later use
data_dtm.to_pickle("dtm.pkl")

In [130]:
# pickle the cleaned data and the CountVectorizer object
data_clean.to_pickle('data_clean.pkl')
pickle.dump(cv, open("cv.pkl", "wb"))

In [131]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.25, random_state = 4)

In [132]:
x_train_countvectorizer = cv.fit_transform(x_train)

In [133]:
# print(x_train[0])
# print(x_train_countvectorizer[0])

In [134]:
mnb = MultinomialNB()

In [135]:
mnb.fit(x_train_countvectorizer, y_train)

MultinomialNB()

In [136]:
x_test_countvectorizer = cv.transform(x_test)

In [137]:
pred = mnb.predict(x_test_countvectorizer)
# print(pred)

In [138]:
rezult = np.array(y_test)
# print(rezult)

In [139]:
count = 0
for i in range(len(pred)):
    if pred[i] == rezult[i]:
        count += 1    

print(count)
print(len(pred))

269
291

In [140]:
accuracy = count/len(pred)
print(accuracy)

0.9243986254295533

In [141]:
# ### The evaluation of coments typed by the user.

test_set = ['zdecydowanie nie polecam tego gównianego sklepu']
new_test = cv.transform(test_set)
prediction = mnb.predict(new_test) # model przewiduje, czy wpisane zdanie jest positive=1, czy negative=0
if prediction == 0:
    print('negative')
else:
    print('positive')

positive

In [142]:
with open(r'C:\Users\User\GIT\model testing\Ocena-komentarzy-NLP\Flask\pickeld_sentiment_classifier.pkl', 'wb') as f:
    pickle.dump(mnb , f)